# Generated by Django 3.2.6 on 2021-08-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=100, verbose_name='BLOG TITLE')),
                ('blog_slug', models.CharField(max_length=200, verbose_name='BLOG SLUG')),
            ],
        ),
    ]
